export const REQUEST_POKEMON = 'REQUEST_POKEMON'
export const REQUEST_POKEMON_FAILED = 'REQUEST_POKEMON_FAILED'
export const REQUEST_POKEMON_SUCCESS = 'REQUEST_POKEMON_SUCCESS'

export const REQUEST_POKEMON_PAGINATION = 'REQUEST_POKEMON_PAGINATION'
export const REQUEST_POKEMON_PAGINATION_FAILED = 'REQUEST_POKEMON_PAGINATION_FAILED'
export const REQUEST_POKEMON_PAGINATION_SUCCESS = 'REQUEST_POKEMON_PAGINATION_SUCCESS'

export const REQUEST_POKEMON_DETAIL = 'REQUEST_POKEMON_DETAIL'
export const REQUEST_POKEMON_DETAIL_FAILED = 'REQUEST_POKEMON_DETAIL_FAILED'
export const REQUEST_POKEMON_DETAIL_SUCCESS = 'REQUEST_POKEMON_DETAIL_SUCCESS'
